
import React, { useState, useMemo } from 'react';
import { CourseData, CourseTab, CapstoneProject, Activity, Worksheet, VideoScript } from '../types';
import { BookOpen, CheckSquare, ClipboardList, PenTool, Printer, ArrowLeft, LayoutList, Calendar, Flag, Clock, Presentation, Puzzle, Video, Download, ExternalLink, Copy, Trophy, Layers, ChevronDown, ChevronUp, FileText, PieChart, BarChart, Code } from 'lucide-react';
import { ModuleImage } from './ModuleImage';
import pptxgen from 'pptxgenjs';

interface CourseViewerProps {
  data: CourseData;
  onBack: () => void;
}

export const CourseViewer: React.FC<CourseViewerProps> = ({ data, onBack }) => {
  const [activeTab, setActiveTab] = useState<CourseTab>(CourseTab.OVERVIEW);
  const [copied, setCopied] = useState(false);
  const [isExportingSlides, setIsExportingSlides] = useState(false);
  const [isBinderView, setIsBinderView] = useState(false);
  
  const handlePrintBinder = () => {
    // Switch to full binder view specifically for printing
    setIsBinderView(true);
    // Give browser time to reflow the single long page
    setTimeout(() => {
      window.print();
      // Revert after printing (most browsers pause execution during print dialog)
      setIsBinderView(false);
    }, 500);
  };

  const handleDownloadHTML = () => {
    const htmlContent = document.documentElement.outerHTML;
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${data.courseTitle.replace(/\s+/g, '_')}_Offline_Course.html`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const copySlidesToClipboard = () => {
    const text = data.slideDeck.map(s => `${s.title}\n${s.bulletPoints.map(b => `- ${b}`).join('\n')}\nSpeaker Notes: ${s.speakerNotes}`).join('\n\n---\n\n');
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportSlides = async () => {
    setIsExportingSlides(true);
    try {
      const pres = new pptxgen();
      pres.title = data.courseTitle;
      pres.subject = "Course Slides";
      pres.layout = 'LAYOUT_16x9';

      let slide = pres.addSlide();
      slide.background = { color: 'F8FAFC' };
      slide.addText(data.courseTitle, { 
        x: 0.5, y: 2, w: '90%', h: 1.5, 
        fontSize: 32, bold: true, align: 'center', color: '1E293B' 
      });
      slide.addText(data.courseDescription || "Generated by CourseCraft AI", { 
        x: 1, y: 4, w: '80%', h: 1, 
        fontSize: 16, align: 'center', color: '64748B' 
      });

      data.slideDeck.forEach((s) => {
        slide = pres.addSlide();
        slide.background = { color: 'FFFFFF' };
        slide.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 1.2, fill: { color: '4F46E5' } });
        slide.addText(s.title, { 
          x: 0.5, y: 0.2, w: '90%', h: 0.8, 
          fontSize: 24, bold: true, color: 'FFFFFF', align: 'left'
        });
        const items = s.bulletPoints.map(bp => ({
            text: bp,
            options: { bullet: true, breakLine: true, fontSize: 18, color: '334155', paraSpaceBefore: 10 }
        }));
        slide.addText(items, { x: 0.5, y: 1.5, w: '90%', h: 4.5, valign: 'top' });
        if (s.speakerNotes) slide.addNotes(s.speakerNotes);
        slide.addText(`CourseCraft AI - ${data.courseTitle}`, { 
            x: 0.5, y: 5.25, w: '90%', h: 0.3, 
            fontSize: 10, color: '94A3B8', align: 'right' 
        });
      });

      await pres.writeFile({ fileName: `${data.courseTitle.replace(/[^a-z0-9]/gi, '_').substring(0, 30)}_Slides.pptx` });
    } catch (e) {
      console.error("Error generating slides", e);
      alert("Could not generate slides. Please try again.");
    } finally {
      setIsExportingSlides(false);
    }
  };

  const allActivities = useMemo(() => data.modules.flatMap(m => m.lessons.flatMap(l => l.activities)), [data.modules]);
  const allWorksheets = useMemo(() => data.modules.flatMap(m => m.lessons.flatMap(l => l.worksheets)), [data.modules]);

  const assetCounts = useMemo(() => ({
    modules: data.modules.length,
    lessons: data.modules.reduce((acc, m) => acc + m.lessons.length, 0),
    activities: allActivities.length,
    worksheets: allWorksheets.length,
    capstones: data.capstoneProjects.length,
    scripts: data.videoScripts.length
  }), [data, allActivities, allWorksheets]);

  const TabButton = ({ tab, icon: Icon, label }: { tab: CourseTab; icon: any; label: string }) => (
    <button
      onClick={() => setActiveTab(tab)}
      className={`flex items-center px-4 py-3 text-sm font-medium border-b-2 transition-colors duration-200 whitespace-nowrap ${
        activeTab === tab
          ? 'border-indigo-600 text-indigo-600'
          : 'border-transparent text-slate-500 hover:text-slate-700 hover:border-slate-300'
      }`}
    >
      <Icon className="w-4 h-4 mr-2" />
      {label}
    </button>
  );

  const renderCapstoneCard = (project: CapstoneProject, index: number) => {
     const scopeColors = {
       'Weekly': 'bg-blue-50 border-blue-200 text-blue-900',
       'Monthly': 'bg-purple-50 border-purple-200 text-purple-900',
       'Quarterly': 'bg-amber-50 border-amber-200 text-amber-900',
       'Yearly': 'bg-rose-50 border-rose-200 text-rose-900',
       'Final': 'bg-pink-50 border-pink-200 text-pink-900'
     };
     const badgeColor = {
       'Weekly': 'bg-blue-100 text-blue-700',
       'Monthly': 'bg-purple-100 text-purple-700',
       'Quarterly': 'bg-amber-100 text-amber-700',
       'Yearly': 'bg-rose-100 text-rose-700',
       'Final': 'bg-pink-100 text-pink-700'
     };
     const colorClass = scopeColors[project.scope] || scopeColors['Final'];
     const badgeClass = badgeColor[project.scope] || badgeColor['Final'];

     return (
        <div key={index} className={`p-6 rounded-lg border ${colorClass.replace('bg-', 'border-')} mb-8 print-avoid-break`}>
          <div className="flex justify-between items-start mb-4">
             <div className="flex flex-col">
                <h3 className="text-2xl font-bold text-slate-900">{project.title}</h3>
                {project.duration && (
                  <span className="flex items-center text-sm text-slate-500 mt-1">
                    <Clock className="w-3 h-3 mr-1" /> Estimated Time: {project.duration}
                  </span>
                )}
             </div>
             <span className={`px-3 py-1 rounded-full text-xs font-bold uppercase ${badgeClass}`}>
               {project.scope} Project
             </span>
          </div>
          <p className="text-slate-700 text-lg leading-relaxed mb-6">{project.description}</p>
          <div className="grid md:grid-cols-2 gap-8 bg-white p-4 rounded-lg bg-opacity-60">
             <div>
                <h4 className="text-lg font-bold text-slate-900 mb-4 flex items-center">
                  <CheckSquare className="w-5 h-5 mr-2 opacity-50" /> Requirements
                </h4>
                <ul className="space-y-2">
                  {project.requirements.map((req, i) => (
                    <li key={i} className="flex items-start">
                      <span className="mr-2 font-bold opacity-50">•</span>
                      <span className="text-sm text-slate-700">{req}</span>
                    </li>
                  ))}
                </ul>
             </div>
             <div>
                <h4 className="text-lg font-bold text-slate-900 mb-4 flex items-center">
                  <LayoutList className="w-5 h-5 mr-2 opacity-50" /> Project Steps
                </h4>
                <div className="space-y-3">
                  {project.steps.map((step, i) => (
                    <div key={i} className="flex">
                      <span className="flex-shrink-0 w-6 h-6 rounded-full bg-slate-200 flex items-center justify-center font-bold text-xs mr-3 mt-0.5 text-slate-600">
                        {i + 1}
                      </span>
                      <span className="text-slate-700 text-sm">{step}</span>
                    </div>
                  ))}
                </div>
             </div>
          </div>
       </div>
     );
  };

  const renderScriptSection = (title: string, scripts: VideoScript[], colorClass: string, icon: any) => {
    if (scripts.length === 0) return null;
    const Icon = icon;
    return (
      <div className="mb-12 print-avoid-break">
        <h3 className={`text-xl font-bold text-slate-900 mb-6 flex items-center pb-2 border-b ${colorClass}`}>
          <Icon className="w-5 h-5 mr-2" />
          {title}
        </h3>
        <div className="space-y-8">
          {scripts.map((script, idx) => (
            <div key={idx} className="print-avoid-break">
              <h4 className="font-bold text-slate-800 mb-2">{script.title}</h4>
              <div className="bg-slate-50 font-mono text-sm p-6 rounded-lg border border-slate-200 whitespace-pre-line text-slate-800 print:bg-transparent print:border-slate-300">
                {script.script}
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  };

  // The Binder view renders EVERYTHING in sequence
  const FullBinderContent = () => (
    <div className="space-y-16">
       {/* Section 1: Syllabus */}
       <div className="print-break-after-always">
          <h1 className="text-4xl font-bold border-b-4 border-indigo-600 pb-4 mb-8">Course Syllabus</h1>
          <div className="grid md:grid-cols-2 gap-8 mb-8">
            <div className="bg-indigo-50 p-6 rounded-lg border border-indigo-100">
              <h3 className="font-bold text-indigo-900 mb-2">Target Audience</h3>
              <p className="text-slate-700">{data.syllabus.targetAudience}</p>
            </div>
            <div className="bg-indigo-50 p-6 rounded-lg border border-indigo-100">
              <h3 className="font-bold text-indigo-900 mb-2">Prerequisites</h3>
              <ul className="list-disc list-inside text-slate-700">
                {data.syllabus.prerequisites.map((req, i) => <li key={i}>{req}</li>)}
              </ul>
            </div>
          </div>
          <h3 className="text-xl font-bold mb-4">Schedule</h3>
          <div className="space-y-4">
             {data.syllabus.schedule.map((item, idx) => (
                <div key={idx} className="p-4 border border-slate-200 rounded-lg">
                   <div className="flex justify-between font-bold text-indigo-600 mb-2">
                      <span>{item.timeframe}</span>
                      <span>{item.deadline}</span>
                   </div>
                   <h4 className="font-bold text-slate-900">{item.topic}</h4>
                   <p className="text-slate-600 text-sm">{item.description}</p>
                </div>
             ))}
          </div>
       </div>

       {/* Section 2: Modules & Lessons */}
       {data.modules.map((m, idx) => (
          <div key={idx} className="print-break-after-always">
             <h2 className="text-3xl font-bold bg-slate-900 text-white p-6 rounded-t-xl mb-4">Module {idx + 1}: {m.title}</h2>
             <p className="text-lg text-slate-600 mb-8 px-6">{m.description}</p>
             <div className="space-y-12">
                {m.lessons.map((l, lIdx) => (
                   <div key={lIdx} className="print-avoid-break px-6 border-l-4 border-slate-200">
                      <h3 className="text-2xl font-bold text-slate-900 mb-4">{l.title} ({l.duration})</h3>
                      <div className="prose max-w-none text-slate-700 whitespace-pre-line bg-slate-50 p-6 rounded-xl">
                        {l.content}
                      </div>
                   </div>
                ))}
             </div>
          </div>
       ))}

       {/* Section 3: Activities & Worksheets */}
       <div className="print-break-after-always">
          <h1 className="text-4xl font-bold border-b-4 border-purple-600 pb-4 mb-8">Worksheets & Activities</h1>
          {allWorksheets.map((w, idx) => (
             <div key={idx} className="print-break-after-always border-2 border-slate-800 p-8 min-h-[10in]">
                <div className="flex justify-between border-b-2 border-slate-800 pb-4 mb-8">
                   <h2 className="text-2xl font-bold">{w.title}</h2>
                   <span className="font-bold uppercase text-slate-400">Page {idx + 1}</span>
                </div>
                <div className="space-y-8">
                   {w.questions.map((q, qIdx) => (
                      <div key={qIdx}>
                         <p className="font-bold mb-2">Q{qIdx + 1}: {q.question}</p>
                         <div className="h-20 border border-slate-300 border-dashed rounded-lg"></div>
                      </div>
                   ))}
                </div>
             </div>
          ))}
       </div>
    </div>
  );

  return (
    <div className={`min-h-screen ${isBinderView ? 'bg-white' : 'bg-slate-50'}`}>
      {/* Header - Hidden on Print or in Binder View */}
      <header className={`bg-white shadow-sm sticky top-0 z-10 no-print ${isBinderView ? 'hidden' : 'block'}`}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center">
              <button onClick={onBack} className="mr-4 text-slate-500 hover:text-indigo-600 transition-colors">
                <ArrowLeft className="w-5 h-5" />
              </button>
              <h1 className="text-xl font-bold text-slate-900 truncate max-w-md">{data.courseTitle}</h1>
            </div>
            <div className="flex space-x-2">
              <button
                onClick={handleDownloadHTML}
                className="inline-flex items-center px-4 py-2 border border-slate-300 rounded-lg shadow-sm text-sm font-medium text-slate-700 bg-white hover:bg-slate-50"
              >
                <Code className="w-4 h-4 mr-2 text-indigo-600" />
                Export HTML
              </button>
              <button
                onClick={handlePrintBinder}
                className="inline-flex items-center px-4 py-2 border border-slate-300 rounded-lg shadow-sm text-sm font-medium text-slate-700 bg-white hover:bg-slate-50"
              >
                <FileText className="w-4 h-4 mr-2 text-red-600" />
                Print PDF Binder
              </button>
            </div>
          </div>
          <div className="flex overflow-x-auto no-scrollbar pb-1">
            <TabButton tab={CourseTab.OVERVIEW} icon={PieChart} label="Overview" />
            <TabButton tab={CourseTab.SYLLABUS} icon={LayoutList} label="Syllabus" />
            <TabButton tab={CourseTab.MODULES} icon={Layers} label="Modules" />
            <TabButton tab={CourseTab.ACTIVITIES} icon={Puzzle} label="Activities" />
            <TabButton tab={CourseTab.WORKSHEET} icon={PenTool} label="Worksheets" />
            <TabButton tab={CourseTab.CAPSTONE} icon={Trophy} label="Capstones" />
            <TabButton tab={CourseTab.SLIDES} icon={Presentation} label="Slides" />
            <TabButton tab={CourseTab.VIDEO_SCRIPTS} icon={Video} label="Scripts" />
            <TabButton tab={CourseTab.ASSETS} icon={Download} label="Assets" />
            <TabButton tab={CourseTab.CHECKLIST} icon={CheckSquare} label="Checklist" />
            <TabButton tab={CourseTab.SOP} icon={ClipboardList} label="SOP" />
          </div>
        </div>
      </header>

      {/* Content Area */}
      <main className={`max-w-5xl mx-auto py-8 px-4 sm:px-6 lg:px-8 ${isBinderView ? 'print:max-w-none print:p-0 print:m-0' : ''}`}>
        
        {/* Binder View - Shown only when printing full binder */}
        {isBinderView ? (
          <FullBinderContent />
        ) : (
          <>
            {/* Standard Tab View Logic */}
            <div className={`${activeTab === CourseTab.OVERVIEW ? 'block' : 'hidden'} no-print`}>
              {/* Infographic Dashboard */}
              <div className="bg-white shadow-xl rounded-2xl overflow-hidden mb-8">
                <div className="bg-indigo-600 p-8 text-white text-center">
                   <h1 className="text-4xl font-bold mb-2">{data.courseTitle}</h1>
                   <p className="text-indigo-100 text-lg max-w-2xl mx-auto">{data.courseDescription}</p>
                </div>
                <div className="p-8">
                   <div className="grid grid-cols-2 md:grid-cols-4 gap-6 mb-12">
                      <div className="text-center p-4 bg-slate-50 rounded-xl border border-slate-100">
                         <Clock className="w-8 h-8 text-indigo-500 mx-auto mb-2" />
                         <div className="text-2xl font-bold text-slate-900">{data.estimatedTotalDuration || "Variable"}</div>
                         <div className="text-xs text-slate-500 uppercase tracking-wider font-bold">Total Time</div>
                      </div>
                      <div className="text-center p-4 bg-slate-50 rounded-xl border border-slate-100">
                         <BookOpen className="w-8 h-8 text-blue-500 mx-auto mb-2" />
                         <div className="text-2xl font-bold text-slate-900">{assetCounts.lessons}</div>
                         <div className="text-xs text-slate-500 uppercase tracking-wider font-bold">Lessons</div>
                      </div>
                      <div className="text-center p-4 bg-slate-50 rounded-xl border border-slate-100">
                         <Puzzle className="w-8 h-8 text-purple-500 mx-auto mb-2" />
                         <div className="text-2xl font-bold text-slate-900">{assetCounts.activities + assetCounts.worksheets}</div>
                         <div className="text-xs text-slate-500 uppercase tracking-wider font-bold">Exercises</div>
                      </div>
                      <div className="text-center p-4 bg-slate-50 rounded-xl border border-slate-100">
                         <Trophy className="w-8 h-8 text-amber-500 mx-auto mb-2" />
                         <div className="text-2xl font-bold text-slate-900">{assetCounts.capstones}</div>
                         <div className="text-xs text-slate-500 uppercase tracking-wider font-bold">Projects</div>
                      </div>
                   </div>
                   <div className="grid md:grid-cols-2 gap-12">
                      <div>
                        <h3 className="text-xl font-bold text-slate-900 mb-6 flex items-center">
                          <Flag className="w-5 h-5 mr-2 text-indigo-600" />
                          Learning Roadmap
                        </h3>
                        <div className="relative border-l-2 border-indigo-100 ml-3 space-y-8 pb-4">
                          {data.syllabus.roadmap.map((step, idx) => (
                            <div key={idx} className="relative pl-8">
                               <div className="absolute -left-[9px] top-1 w-4 h-4 rounded-full bg-indigo-600 border-2 border-white shadow-sm"></div>
                               <h4 className="font-bold text-slate-900">Phase {idx + 1}</h4>
                               <p className="text-slate-600 text-sm">{step}</p>
                            </div>
                          ))}
                        </div>
                      </div>
                      <div>
                         <h3 className="text-xl font-bold text-slate-900 mb-6 flex items-center">
                           <BarChart className="w-5 h-5 mr-2 text-indigo-600" />
                           Asset Inventory
                         </h3>
                         <div className="space-y-4">
                            <div className="flex justify-between items-center p-3 bg-slate-50 rounded-lg">
                               <span className="flex items-center text-slate-700">
                                 <Layers className="w-4 h-4 mr-2 opacity-50" /> Modules
                               </span>
                               <span className="font-bold text-slate-900">{assetCounts.modules}</span>
                            </div>
                            <div className="flex justify-between items-center p-3 bg-slate-50 rounded-lg">
                               <span className="flex items-center text-slate-700">
                                 <Puzzle className="w-4 h-4 mr-2 opacity-50" /> Activities
                               </span>
                               <span className="font-bold text-slate-900">{assetCounts.activities}</span>
                            </div>
                            <div className="flex justify-between items-center p-3 bg-slate-50 rounded-lg">
                               <span className="flex items-center text-slate-700">
                                 <PenTool className="w-4 h-4 mr-2 opacity-50" /> Worksheets
                               </span>
                               <span className="font-bold text-slate-900">{assetCounts.worksheets}</span>
                            </div>
                            <div className="flex justify-between items-center p-3 bg-slate-50 rounded-lg">
                               <span className="flex items-center text-slate-700">
                                 <Presentation className="w-4 h-4 mr-2 opacity-50" /> Slide Deck
                               </span>
                               <span className="font-bold text-slate-900">{data.slideDeck.length}</span>
                            </div>
                         </div>
                      </div>
                   </div>
                </div>
              </div>
            </div>

            {/* Other Tabs */}
            <div className={activeTab === CourseTab.SYLLABUS ? 'block' : 'hidden'}>
               <div className="bg-white p-8 rounded-xl shadow-sm border border-slate-200">
                  <h2 className="text-2xl font-bold mb-4">Syllabus</h2>
                  <div className="space-y-6">
                     <div>
                        <h3 className="font-bold text-slate-900 mb-2">Target Audience</h3>
                        <p className="text-slate-600">{data.syllabus.targetAudience}</p>
                     </div>
                     <div>
                        <h3 className="font-bold text-slate-900 mb-2">Learning Objectives</h3>
                        <ul className="list-disc list-inside text-slate-600">
                           {data.syllabus.learningObjectives.map((o, i) => <li key={i}>{o}</li>)}
                        </ul>
                     </div>
                  </div>
               </div>
            </div>

            <div className={activeTab === CourseTab.MODULES ? 'block' : 'hidden'}>
              {data.modules.map((m, idx) => (
                <div key={idx} className="mb-8 bg-white p-8 rounded-xl shadow-sm border border-slate-200">
                   <h2 className="text-2xl font-bold text-indigo-600 mb-4">{m.title}</h2>
                   <p className="text-slate-600 mb-8">{m.description}</p>
                   <div className="space-y-8">
                     {m.lessons.map((l, lIdx) => (
                        <div key={lIdx} className="p-6 bg-slate-50 rounded-xl border border-slate-100">
                           <h3 className="text-xl font-bold mb-4">{l.title}</h3>
                           <ModuleImage prompt={l.imagePrompt} alt={l.title} />
                           <div className="prose text-slate-700 whitespace-pre-line">{l.content}</div>
                        </div>
                     ))}
                   </div>
                </div>
              ))}
            </div>

            <div className={activeTab === CourseTab.ACTIVITIES ? 'block' : 'hidden'}>
               <div className="space-y-6">
                  {allActivities.map((a, idx) => (
                     <div key={idx} className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                        <div className="flex justify-between font-bold text-purple-600 mb-4">
                           <span>{a.title}</span>
                           <span>{a.duration}</span>
                        </div>
                        <p className="text-sm text-slate-500 mb-2">Objective: {a.objective}</p>
                        <div className="text-slate-700">{a.instructions}</div>
                     </div>
                  ))}
               </div>
            </div>

            <div className={activeTab === CourseTab.WORKSHEET ? 'block' : 'hidden'}>
               <div className="space-y-8">
                  {allWorksheets.map((w, idx) => (
                     <div key={idx} className="bg-white p-8 rounded-xl border border-slate-200 shadow-sm">
                        <h3 className="text-xl font-bold mb-4">{w.title}</h3>
                        <div className="space-y-6">
                           {w.questions.map((q, qIdx) => (
                              <div key={qIdx}>
                                 <p className="font-medium text-slate-800 mb-2">Q{qIdx+1}: {q.question}</p>
                                 <div className="h-12 border-b border-slate-200"></div>
                              </div>
                           ))}
                        </div>
                     </div>
                  ))}
               </div>
            </div>

            <div className={activeTab === CourseTab.CAPSTONE ? 'block' : 'hidden'}>
               {data.capstoneProjects.map((p, idx) => renderCapstoneCard(p, idx))}
            </div>

            <div className={activeTab === CourseTab.SLIDES ? 'block' : 'hidden'}>
               <div className="flex justify-between items-center mb-6">
                  <h2 className="text-2xl font-bold">Presentation Slides</h2>
                  <button onClick={handleExportSlides} disabled={isExportingSlides} className="px-4 py-2 bg-indigo-600 text-white rounded-lg text-sm font-bold flex items-center">
                     <Presentation className="w-4 h-4 mr-2" />
                     {isExportingSlides ? "Generating..." : "Download PowerPoint"}
                  </button>
               </div>
               <div className="space-y-12">
                  {data.slideDeck.map((s, idx) => (
                     <div key={idx} className="bg-slate-900 text-white rounded-xl aspect-video p-12 flex flex-col justify-center">
                        <h3 className="text-4xl font-bold mb-8">{s.title}</h3>
                        <ul className="space-y-4">
                           {s.bulletPoints.map((bp, bIdx) => <li key={bIdx} className="text-2xl text-slate-300">• {bp}</li>)}
                        </ul>
                     </div>
                  ))}
               </div>
            </div>

            <div className={activeTab === CourseTab.VIDEO_SCRIPTS ? 'block' : 'hidden'}>
               {data.videoScripts.map((s, idx) => (
                  <div key={idx} className="mb-8 bg-white p-6 rounded-xl border border-slate-200">
                     <h3 className="font-bold text-red-600 mb-2">{s.title} ({s.type})</h3>
                     <div className="bg-slate-50 p-6 rounded-lg font-mono text-sm whitespace-pre-line">{s.script}</div>
                  </div>
               ))}
            </div>

            <div className={activeTab === CourseTab.ASSETS ? 'block' : 'hidden'}>
               <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {data.digitalAssets.map((a, idx) => (
                     <div key={idx} className="bg-white p-6 rounded-xl border border-slate-200">
                        <h3 className="font-bold mb-2">{a.title}</h3>
                        <div className="bg-slate-50 p-4 rounded text-sm text-slate-600 select-all">{a.content}</div>
                     </div>
                  ))}
               </div>
            </div>

            <div className={activeTab === CourseTab.CHECKLIST ? 'block' : 'hidden'}>
               <div className="bg-white p-8 rounded-xl shadow-sm border border-slate-200">
                  <h2 className="text-2xl font-bold mb-6">Action Checklist</h2>
                  <div className="space-y-4">
                     {data.checklist.map((item, idx) => (
                        <div key={idx} className="flex items-center space-x-3 p-3 bg-slate-50 rounded-lg">
                           <div className="w-5 h-5 border-2 border-slate-300 rounded"></div>
                           <span className="text-slate-700">{item}</span>
                        </div>
                     ))}
                  </div>
               </div>
            </div>

            <div className={activeTab === CourseTab.SOP ? 'block' : 'hidden'}>
               <div className="space-y-8">
                  <div className="bg-white p-8 rounded-xl border border-slate-200 shadow-sm">
                     <h3 className="text-xl font-bold mb-4">Instructor SOP</h3>
                     <p className="text-sm text-slate-500 mb-6">{data.teacherSop.purpose}</p>
                     <div className="space-y-4">
                        {data.teacherSop.steps.map(s => (
                           <div key={s.stepNumber} className="flex space-x-4 p-4 bg-slate-50 rounded-lg">
                              <span className="font-bold text-indigo-600">{s.stepNumber}</span>
                              <div>
                                 <h4 className="font-bold">{s.action}</h4>
                                 <p className="text-sm text-slate-600">{s.detail}</p>
                              </div>
                           </div>
                        ))}
                     </div>
                  </div>
               </div>
            </div>
          </>
        )}
      </main>

      <footer className="bg-white border-t border-slate-200 mt-12 py-8 no-print">
        <div className="max-w-7xl mx-auto px-4 text-center text-slate-500 text-sm">
          <p>Generated by CourseCraft AI. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
};
